slice_name: t_oil - 2010 - Production Pie Chart2
viz_type: pie
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    expressionType: SQL
    filterOptionName: filter_0foydb85nq3i_n75bt3u324q
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: date = to_date('2010-01-01'::text, 'YYYY-MM-DD'::text)
    subject: null
  color_scheme: supersetColors
  datasource: 1__table
  date_format: smart_date
  extra_form_data: {}
  granularity_sqla: date
  groupby:
  - region
  - country
  innerRadius: 30
  label_type: key
  labels_outside: true
  legendOrientation: top
  legendType: scroll
  metric:
    aggregate: SUM
    column:
      certification_details: null
      certified_by: null
      column_name: production
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 4
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(production)
    optionName: metric_a8cznac03jh_b0g7ou85gaf
    sqlExpression: null
  number_format: SMART_NUMBER
  outerRadius: 70
  row_limit: 100
  show_labels: true
  show_labels_threshold: 5
  sort_by_metric: true
  time_range: No filter
  viz_type: pie
